version: 2.1

jobs:
  checkout:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Checkout"
          command: "echo Hello, World!"
  build-java:
    docker:
      - image: eclipse-temurin:17.0.8.1_1-jdk
    steps:
      - checkout
      - run:
          name: build demo
          command: mvn -f demo/pom.xml clean install

workflows:
  build:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - feature
      - build-java:
          requires:
            - checkout